-- Day 06: Multi-table Joins
-- Focus:
-- joining more than two tables
-- Recommended dataset:
-- customers(customer_id, customer_name)
-- orders(order_id, customer_id, order_date)
-- order_items(order_id, product_id, quantity)
-- products(product_id, product_name, price)

-- Questions
-- 1. Show each order with customer name.
-- 2. Show each ordered product with customer name.
-- 3. Calculate total order amount for each order.
-- 4. Find total revenue generated by each customer.
-- 5. Find the most purchased product by quantity.

