-- Write bronze/raw table DDL in this file.
-- Bronze means source-aligned raw tables with minimal cleanup.
--
-- Create raw tables for the Olist CSV files from `data/raw/olist/`.
--
-- Recommended first tables:
-- 1. bronze.raw_orders
-- 2. bronze.raw_order_items
-- 3. bronze.raw_customers
-- 4. bronze.raw_products
-- 5. bronze.raw_sellers
-- 6. bronze.raw_order_payments
-- 7. bronze.raw_order_reviews
--
-- In this file, decide:
-- 1. column names
-- 2. data types
-- 3. primary keys if you want them on raw tables
